### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by Elbar** [akoikelov/AdvancedSymfony#1]
#### PHP Fatal error:  Class 'AKoikelovAS\AppBundle\AKoikelovASAppBundle' not found in /opt/lampp/htdocs/adsymfony/app/AppKernel.php on line 21

![screen1](https://cloud.githubusercontent.com/assets/10593442/11491114/2a06ad30-9809-11e5-8486-301ba6e3e674.png)
![screen2](https://cloud.githubusercontent.com/assets/10593442/11491118/337b864c-9809-11e5-95ba-787ea7df7d7c.png)

**Comment by Elbar** [comment]
I have cleaned the cache by the following command: 
<quote>app/console cache:clear</quote>
but it doesn't work?!

**Comment by akoikelov** [comment]
![issue1](https://cloud.githubusercontent.com/assets/10974851/11502541/a7cb1b46-9865-11e5-8d63-8e53a101fb03.png)
